### ISSUE TITLE
Bidirectional scanning PTU sample files?

### ISSUE THREAD

**Issue by cgohlke** [RobertMolenaar-UT/fastFLIM#1]
Hello. I noticed that your package supports PTU files acquired with bidirectional scanning. I am trying to support decoding bidirectional scanning in the [ptufile](https://github.com/cgohlke/ptufile) Python library, but have been unable to obtain any such files for testing. Would you be able to share such files? Thank you.

**Comment by RobertMolenaar-UT** [comment]
Hi Christoph , I try to find you a nice picture measured with the Bidirectional scanning this week. Note that when you use Flimbee scanner in bidirectional mode, there is some hysteresis between the odd and even lines (that is scan rate dependent) in experiment you need to set it correctly. However that is not always correct. So in [ReadPTU-bidirect](https://github.com/RobertMolenaar-UT/fastFLIM/blob/main/readPTU_FLIM_bidirect.py) Is pass a bi-shift variable. That works at pixel value, but perhaps I need to change it to subpixel.

I will try to find you this week one or some examples. 
FYI information I modified PTU_reader 3 months ago, not all PTU header data was passed, now it does. 
Known feature bug, it cannot extract single frames measured from a multi-frame image. useful for kinetics.
Robert

**Comment by cgohlke** [comment]
Hi Robert. That's very helpful. Thank you.

**Comment by cgohlke** [comment]
Thank you for privately sharing the sample files!
